# Generated by Django 4.2.7 on 2023-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='duration',
            field=models.TimeField(),
        ),
    ]
